# VerticalPodAutoscaler configurations for all agents

# VPA for Agent 2 Backend
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: booking-agent2-backend-vpa
  namespace: booking-system
  labels:
    app: booking-agent2
    component: backend
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-agent2-backend
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: backend
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 4000m
        memory: 8Gi
      controlledResources: ["cpu", "memory"]
---
# VPA for Agent 2 Frontend
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: booking-agent2-frontend-vpa
  namespace: booking-system
  labels:
    app: booking-agent2
    component: frontend
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-agent2-frontend
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: frontend
      minAllowed:
        cpu: 50m
        memory: 128Mi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
---
# VPA for Agent 3 Backend
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: booking-agent3-backend-vpa
  namespace: booking-system
  labels:
    app: booking-agent3
    component: backend
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-agent3-backend
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: backend
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 4000m
        memory: 8Gi
      controlledResources: ["cpu", "memory"]
---
# VPA for Agent 3 Frontend
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: booking-agent3-frontend-vpa
  namespace: booking-system
  labels:
    app: booking-agent3
    component: frontend
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-agent3-frontend
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: frontend
      minAllowed:
        cpu: 50m
        memory: 128Mi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
---
# VPA for Agent 4 Backend  
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: booking-agent4-backend-vpa
  namespace: booking-system
  labels:
    app: booking-agent4
    component: backend
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-agent4-backend
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: backend
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 4000m
        memory: 8Gi
      controlledResources: ["cpu", "memory"]
---
# VPA for Agent 4 Frontend
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: booking-agent4-frontend-vpa
  namespace: booking-system
  labels:
    app: booking-agent4
    component: frontend
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-agent4-frontend
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: frontend
      minAllowed:
        cpu: 50m
        memory: 128Mi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
---
# VPA for Sub-Agent S1 (Senior Developer)
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: booking-sub-s1-vpa
  namespace: booking-system
  labels:
    app: booking-sub-s1
    component: claude-agent
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-sub-s1
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: claude-agent
      minAllowed:
        cpu: 200m
        memory: 256Mi
      maxAllowed:
        cpu: 4000m
        memory: 8Gi
      controlledResources: ["cpu", "memory"]
---
# VPA for Sub-Agent S2 (UI Developer)
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: booking-sub-s2-vpa
  namespace: booking-system
  labels:
    app: booking-sub-s2
    component: claude-agent
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-sub-s2
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: claude-agent
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
---
# VPA for Sub-Agent S3 (UX Expert)
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: booking-sub-s3-vpa
  namespace: booking-system
  labels:
    app: booking-sub-s3
    component: claude-agent
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-sub-s3
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: claude-agent
      minAllowed:
        cpu: 50m
        memory: 128Mi
      maxAllowed:
        cpu: 1500m
        memory: 3Gi
      controlledResources: ["cpu", "memory"]
---
# VPA for Sub-Agent S4 (Test Expert)
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: booking-sub-s4-vpa
  namespace: booking-system
  labels:
    app: booking-sub-s4
    component: claude-agent
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-sub-s4
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: claude-agent
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
---
# VPA for Sub-Agent S5 (Architecture Expert)
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: booking-sub-s5-vpa
  namespace: booking-system
  labels:
    app: booking-sub-s5
    component: claude-agent
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-sub-s5
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: claude-agent
      minAllowed:
        cpu: 200m
        memory: 256Mi
      maxAllowed:
        cpu: 4000m
        memory: 8Gi
      controlledResources: ["cpu", "memory"]
---
# VPA for Sub-Agent S6 (DevOps Expert)
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: booking-sub-s6-vpa
  namespace: booking-system
  labels:
    app: booking-sub-s6
    component: claude-agent
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-sub-s6
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: claude-agent
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]