# AUTOMATISCH GENERIERT - NICHT MANUELL BEARBEITEN!
# Generiert von: generate-agent-configs.sh am Di 29. Jul 20:49:55 CEST 2025
# Template: docker-compose.agent-template.yml
# Agent: 2 | Ports: 60201/60202/60203/60204

services:
  postgres-agent2:
    image: postgres:16-alpine
    container_name: booking-postgres-agent2
    environment:
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_password
      POSTGRES_DB: booking_agent2
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "60203:5432"  # Agent 2 PostgreSQL Port
    volumes:
      - postgres_agent2_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booking_user -d booking_agent2"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - booking-agent2-network

  backend-agent2:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: booking-api-agent2
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: "Host=postgres-agent2;Port=5432;Database=booking_agent2;Username=booking_user;Password=booking_password"
      CorsSettings__AllowedOrigins__0: "http://localhost:60201"
      JwtSettings__Secret: "development-jwt-secret-key-for-agent2-testing-only-256-bits-minimum"
      JwtSettings__Issuer: "BookingApi-Agent2"
      JwtSettings__Audience: "BookingApp-Agent2"
      JwtSettings__ExpirationMinutes: "480"
    ports:
      - "60202:80"  # Agent 2 Backend Port
    depends_on:
      postgres-agent2:
        condition: service_healthy
        restart: true
    volumes:
      - ./src/backend:/app/src:ro
    networks:
      - booking-agent2-network
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ../booking-agent2/src/backend
          ignore:
            - bin/
            - obj/
            - "**/*.pdb"

  frontend-agent2:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.dev
    container_name: booking-frontend-agent2
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:60202/api"
      PORT: "3000"
    ports:
      - "60201:3000"  # Agent 2 Frontend Port
    volumes:
      - ./src/frontend:/app:cached
      - /app/node_modules
      - /app/.next
    networks:
      - booking-agent2-network
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ../booking-agent2/src/frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
            - "**/*.log"

  # pgweb Database Web Interface (Development Only)
  pgweb-agent2:
    image: sosedoff/pgweb:latest
    container_name: booking-pgweb-agent2
    environment:
      PGWEB_DATABASE_URL: "postgres://booking_user:booking_password@postgres-agent2:5432/booking_agent2?sslmode=disable"
      PGWEB_AUTH_USER: "admin"
      PGWEB_AUTH_PASS: "admin"
      PGWEB_LISTEN_ADDR: "0.0.0.0"
      PGWEB_LISTEN_PORT: "8081"
    ports:
      - "60204:8081"  # Agent 2 pgweb Port
    depends_on:
      postgres-agent2:
        condition: service_healthy
        restart: true
    networks:
      - booking-agent2-network
    restart: unless-stopped
    profiles:
      - development  # Only available in development environment

volumes:
  postgres_agent2_data:

networks:
  booking-agent2-network:
    driver: bridge
    name: booking-agent2-network