# Testing Docker Compose Override
# Use with: docker-compose -f docker-compose.yml -f docker-compose.test.yml up

version: '3.8'

services:
  api:
    environment:
      # Testing environment settings
      ASPNETCORE_ENVIRONMENT: Testing
      
      # Testing seeding configuration - full seeding enabled
      SeedingSettings__EnableSeeding: "true"
      SeedingSettings__EnableBasicSeeding: "true"
      SeedingSettings__EnableComprehensiveSeeding: "true"     # Enable test data
      SeedingSettings__ForceComprehensiveSeeding: "true"      # Override environment restrictions
      SeedingSettings__EnableSeedingLogs: "true"              # Detailed logs for debugging
      
      # Test database connection
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=booking_test;Username=booking_user;Password=booking_password"
      
      # Testing-specific JWT settings
      JwtSettings__Secret: "test-jwt-secret-for-integration-tests-min-256-bits"
      JwtSettings__ExpirationMinutes: "60"
      
    # Override ports to avoid conflicts during testing
    ports:
      - "5001:80"
      
    # Add test-specific health check
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    environment:
      # Test database settings
      POSTGRES_DB: booking_test
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_password
      
    # Use separate test volume
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      
    # Override port to avoid conflicts
    ports:
      - "5433:5432"
      
    # Faster startup for testing
    command: >
      postgres 
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.max=10000
      -c pg_stat_statements.track=all
      -c max_connections=100
      -c shared_buffers=128MB
      -c effective_cache_size=256MB

volumes:
  postgres_test_data:
    # Temporary volume for testing
    driver: local